### PR TITLE
Use `replaceAll`, fixes #4

### LINKED ISSUE #4: Only adds cache buster once per item per file

### PR DESCRIPTION
**Pull request by BenjaminEHowe**
Fixes #4.

Note that I haven't tested this as well as I would like -- please test it before merging and releasing!

Also replaced string concatenation with a template literal because IMO it's easier to read.

### CODE REVIEW

**Comment by Denperidge** [comment]
Oh! I should honestly just write some tests, might be overdue and make future maintenance easier

**Comment by BenjaminEHowe** [comment]
Perhaps, but [I'm not really qualified to comment on missing tests](https://github.com/BenjaminEHowe/beh.uk?tab=readme-ov-file#tests). In my defence I don't really work with Node.js – learning more about testing using the stack (both BE and FE) is on my "want to learn" list.

**Comment by Denperidge** [comment]
Understandable! No worries, I'm trying to cook up a very rudimentary-but-hopefully-enough test

**Comment by BenjaminEHowe** [comment]
More than happy to pair on adding tests if you'd like -- if nothing else it would help me to learn something new :-)

**Comment by Denperidge** [comment]
Sounds good! A bit is on the dev branch already, but not finished. Feel free to throw me any chat platforms you prefer to use on my email @BenjaminEHowe

**Comment by Denperidge** [comment]
Tests, even if written a bit peculiar, are written *and* passing again since adding your commits! Thanks for opening the issue and pr 😄

**Pull request merged**
